"""Markpact configuration management with .env support"""

import os
from pathlib import Path
from typing import Optional

# Default .env location
DEFAULT_ENV_PATH = Path.home() / ".markpact" / ".env"

# Default configuration
DEFAULTS = {
    "MARKPACT_MODEL": "ollama/qwen2.5-coder:14b",
    "MARKPACT_API_BASE": "http://localhost:11434",
    "MARKPACT_API_KEY": "",
    "MARKPACT_TEMPERATURE": "0.7",
    "MARKPACT_MAX_TOKENS": "4096",
}

# Provider presets
PROVIDER_PRESETS = {
    "ollama": {
        "MARKPACT_MODEL": "ollama/qwen2.5-coder:14b",
        "MARKPACT_API_BASE": "http://localhost:11434",
        "MARKPACT_API_KEY": "",
    },
    "openrouter": {
        "MARKPACT_MODEL": "openrouter/nvidia/nemotron-3-nano-30b-a3b:free",
        "MARKPACT_API_BASE": "https://openrouter.ai/api/v1",
        "MARKPACT_API_KEY": "",  # User must provide
    },
    "openai": {
        "MARKPACT_MODEL": "gpt-4o-mini",
        "MARKPACT_API_BASE": "https://api.openai.com/v1",
        "MARKPACT_API_KEY": "",  # User must provide
    },
    "anthropic": {
        "MARKPACT_MODEL": "claude-3-haiku-20240307",
        "MARKPACT_API_BASE": "https://api.anthropic.com",
        "MARKPACT_API_KEY": "",  # User must provide
    },
    "groq": {
        "MARKPACT_MODEL": "groq/llama-3.1-70b-versatile",
        "MARKPACT_API_BASE": "https://api.groq.com/openai/v1",
        "MARKPACT_API_KEY": "",  # User must provide
    },
}


def get_env_path() -> Path:
    """Get the .env file path (can be overridden by MARKPACT_ENV_PATH)"""
    return Path(os.environ.get("MARKPACT_ENV_PATH", DEFAULT_ENV_PATH))


def ensure_config_dir() -> Path:
    """Ensure config directory exists"""
    config_dir = get_env_path().parent
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir


def load_env() -> dict[str, str]:
    """Load configuration from .env file"""
    env_path = get_env_path()
    config = DEFAULTS.copy()
    
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                config[key] = value
    
    # Override with environment variables
    for key in DEFAULTS:
        if key in os.environ:
            config[key] = os.environ[key]
    
    return config


def save_env(config: dict[str, str]) -> Path:
    """Save configuration to .env file"""
    ensure_config_dir()
    env_path = get_env_path()
    
    lines = [
        "# Markpact LLM Configuration",
        "# Generated by: markpact config",
        "",
        "# LLM Model (e.g., ollama/qwen2.5-coder:14b, openrouter/meta-llama/llama-3-70b)",
        f'MARKPACT_MODEL="{config.get("MARKPACT_MODEL", DEFAULTS["MARKPACT_MODEL"])}"',
        "",
        "# API Base URL",
        f'MARKPACT_API_BASE="{config.get("MARKPACT_API_BASE", DEFAULTS["MARKPACT_API_BASE"])}"',
        "",
        "# API Key (required for cloud providers like OpenRouter, OpenAI)",
        f'MARKPACT_API_KEY="{config.get("MARKPACT_API_KEY", "")}"',
        "",
        "# Generation parameters",
        f'MARKPACT_TEMPERATURE="{config.get("MARKPACT_TEMPERATURE", DEFAULTS["MARKPACT_TEMPERATURE"])}"',
        f'MARKPACT_MAX_TOKENS="{config.get("MARKPACT_MAX_TOKENS", DEFAULTS["MARKPACT_MAX_TOKENS"])}"',
        "",
    ]
    
    env_path.write_text("\n".join(lines))
    return env_path


def init_env(force: bool = False) -> tuple[Path, bool]:
    """Initialize .env file with defaults if it doesn't exist.
    
    Returns:
        Tuple of (path, created) where created is True if file was created
    """
    env_path = get_env_path()
    
    if env_path.exists() and not force:
        return env_path, False
    
    save_env(DEFAULTS)
    return env_path, True


def set_config(key: str, value: str) -> dict[str, str]:
    """Set a single configuration value"""
    config = load_env()
    config[key] = value
    save_env(config)
    return config


def set_model(model: str) -> dict[str, str]:
    """Set the LLM model"""
    return set_config("MARKPACT_MODEL", model)


def set_api_key(api_key: str) -> dict[str, str]:
    """Set the API key"""
    return set_config("MARKPACT_API_KEY", api_key)


def set_api_base(api_base: str) -> dict[str, str]:
    """Set the API base URL"""
    return set_config("MARKPACT_API_BASE", api_base)


def apply_preset(provider: str, api_key: Optional[str] = None) -> dict[str, str]:
    """Apply a provider preset configuration"""
    if provider not in PROVIDER_PRESETS:
        raise ValueError(f"Unknown provider: {provider}. Available: {', '.join(PROVIDER_PRESETS.keys())}")
    
    config = load_env()
    preset = PROVIDER_PRESETS[provider]
    
    for key, value in preset.items():
        config[key] = value
    
    if api_key:
        config["MARKPACT_API_KEY"] = api_key
    
    save_env(config)
    return config


def show_config() -> str:
    """Show current configuration as formatted string"""
    config = load_env()
    env_path = get_env_path()
    
    lines = [
        f"Config file: {env_path}",
        f"  Exists: {env_path.exists()}",
        "",
        "Current settings:",
    ]
    
    for key, value in config.items():
        if key == "MARKPACT_API_KEY" and value:
            # Mask API key
            display_value = value[:8] + "..." + value[-4:] if len(value) > 12 else "***"
        else:
            display_value = value or "(not set)"
        lines.append(f"  {key}={display_value}")
    
    return "\n".join(lines)


def list_providers() -> str:
    """List available provider presets"""
    lines = ["Available providers:", ""]
    
    for name, preset in PROVIDER_PRESETS.items():
        model = preset.get("MARKPACT_MODEL", "")
        api_base = preset.get("MARKPACT_API_BASE", "")
        needs_key = "Yes" if name != "ollama" else "No (local)"
        lines.append(f"  {name}:")
        lines.append(f"    Model: {model}")
        lines.append(f"    API Base: {api_base}")
        lines.append(f"    Needs API Key: {needs_key}")
        lines.append("")
    
    return "\n".join(lines)
